# Generated by Django 5.0.6 on 2024-05-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_conversation_message_user_conv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conv_id',
            new_name='conv',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='user_conv',
            old_name='conv_id',
            new_name='conv',
        ),
        migrations.RenameField(
            model_name='user_conv',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_id',
        ),
    ]
