# Generated by Django 5.0.6 on 2024-05-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_conv_id_message_conv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_conv',
            name='name',
        ),
    ]
